### ISSUE TITLE
QueryClient issue

### ISSUE THREAD

**Issue by Nirgali42** [sijad/flarum-ext-auth-steam#4]
Getting the following error:

PHP Fatal error:  Class 'Guzzle\Http\QueryString' not found in ./flarum/vendor/sijad/flarum-ext-auth-steam/src/SteamAuthController.php

The directory is there and is referenced in composer json/lock

./flarum/vendor/guzzlehttp/guzzle

```
"require": {
    "guzzlehttp/guzzle": "^6.2"

        "name": "guzzlehttp/guzzle",
        "version": "6.2.1",
        "source": {
            "type": "git",
            "url": "https://github.com/guzzle/guzzle.git",
```

**Comment by XimmersiveX** [comment]
I am getting the same error. I am in no way a programmer so I'm really not sure if it is me doing something wrong.

I use compose on a local machine to get Flarum and this extension then zip it all up and upload it to my web host to to get it all setup. Flarum works fine so far but this extension gives me the error listed above.

If there is something I need to do on my local machine first I would appreciate any kind of directions.

**Comment by sijad** [comment]
please update to new version, thanks for reporting
