### ISSUE TITLE
wrong label on button

### ISSUE THREAD

**Issue by ghost** [sijad/flarum-ext-auth-steam#5]
https://nuclearservers.ga/

(click login and you will see)

**Comment by sijad** [comment]
what should it be?

<img width="421" alt="screen shot 2016-10-13 at 8 45 44 pm" src="https://cloud.githubusercontent.com/assets/7693001/19359202/0906fc94-9186-11e6-87bb-be1974af5281.png">

**Comment by ghost** [comment]
Looks like this for me
http://imgur.com/a/uvFtN

**Comment by sijad** [comment]
try with another browser or clear your current browser cache and try again.

**Comment by ghost** [comment]
I tried chrome and this was my first visit from mobile, what browser are you using?

**Comment by sijad** [comment]
I use chrome, I think this is because of browser cache, you also can try removing all `*.js` files which are placed in `assets` folder.

**Comment by ghost** [comment]
Will try tomorrow

**Comment by ghost** [comment]
Ps: and I will make czech translation for your plugin

**Comment by ghost** [comment]
Cleared cache removed js files still same

**Comment by ghost** [comment]
looks like it was cloudflare caching problem it even fixed my avatar and the steam auth
